#ifndef WISUN_TEST_CERTIFICATES_H_
#define WISUN_TEST_CERTIFICATES_H_
#include <stdint.h>

const uint8_t WISUN_ROOT_CERTIFICATE[] = {
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIBpDCCAUmgAwIBAgIUa47AzAzsSo08mRfkyIyhh3epIIAwCgYIKoZIzj0EAwIw\r\n"
    "HjEcMBoGA1UEAwwTV2ktU1VOIERlbW8gUm9vdCBDQTAgFw0yNDA0MjUwMzQ4MjJa\r\n"
    "GA85OTk5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTV2ktU1VOIERlbW8gUm9vdCBD\r\n"
    "QTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIQklzU8Hz2rwByZ0MgKZOWarZsQ\r\n"
    "9YXhdzUwPbTuH3prAl9IhUHlpgteBYb5GtKwbdHwaD/hCh6JxS4dta19cHWjYzBh\r\n"
    "MBIGA1UdEwEB/wQIMAYBAf8CAQIwCwYDVR0PBAQDAgEGMB0GA1UdDgQWBBRG3bgd\r\n"
    "oVeek7vYqUsMz8s++5FcSTAfBgNVHSMEGDAWgBRG3bgdoVeek7vYqUsMz8s++5Fc\r\n"
    "STAKBggqhkjOPQQDAgNJADBGAiEAkZSPfwpijNAxZBVFf9Q8Cy4bIiYD/zPcUw7O\r\n"
    "qmf5RDICIQDrEjmPN6TwAY0CuciUu62DtCvLNSHygfo59rRgg8PeoQ==\r\n"
    "-----END CERTIFICATE-----\r\n"
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIBrTCCAVOgAwIBAgIUPsMnIkQEvkAVt9mYjVKrB9q/93YwCgYIKoZIzj0EAwIw\r\n"
    "HjEcMBoGA1UEAwwTV2ktU1VOIERlbW8gUm9vdCBDQTAgFw0yNDA0MjUwMzQ4MjVa\r\n"
    "GA85OTk5MTIzMTIzNTk1OVowKDEmMCQGA1UEAwwdV2ktU1VOIERlbW8gSW50ZXJt\r\n"
    "ZWRpYXRlIDEgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASdezBSwpr6+ZHm\r\n"
    "DiTqic3OSJm4aIBnr3hJtPQLf2SAnZMKbjQSpfIsM0Hmu1w3ACHl2jJE7JQoB7ql\r\n"
    "ijRNPuDAo2MwYTASBgNVHRMBAf8ECDAGAQH/AgEBMAsGA1UdDwQEAwIBBjAdBgNV\r\n"
    "HQ4EFgQUqHA6pcTDG0tE59Yq5CyQrUn9yegwHwYDVR0jBBgwFoAURt24HaFXnpO7\r\n"
    "2KlLDM/LPvuRXEkwCgYIKoZIzj0EAwIDSAAwRQIhAPY+xsw3RIs0mdanOA/4iIMn\r\n"
    "LoWb8YLw6bYEAb8VgSMSAiAbo9jTj/le/dL9iwH3i2w0sfnhjaw8/PszV/SR6jan\r\n"
    "hQ==\r\n"
    "-----END CERTIFICATE-----\r\n"
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIBtzCCAV2gAwIBAgIUVarfvVD+tmPamjsV7pC1RbZm7l8wCgYIKoZIzj0EAwIw\r\n"
    "KDEmMCQGA1UEAwwdV2ktU1VOIERlbW8gSW50ZXJtZWRpYXRlIDEgQ0EwIBcNMjQw\r\n"
    "NDI1MDM0ODI2WhgPOTk5OTEyMzEyMzU5NTlaMCgxJjAkBgNVBAMMHVdpLVNVTiBE\r\n"
    "ZW1vIEludGVybWVkaWF0ZSAyIENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE\r\n"
    "NJqpQE0zlYy73prI9XNQfklPm/FK5KuKYnyLH0AkuULWsZJdDdzWzvuFKuzvUkwF\r\n"
    "gt+vwbDHe0S08xXy7kj9KKNjMGEwEgYDVR0TAQH/BAgwBgEB/wIBADALBgNVHQ8E\r\n"
    "BAMCAQYwHQYDVR0OBBYEFOPVSSLENG9x2AfTXLR5M119YKtPMB8GA1UdIwQYMBaA\r\n"
    "FKhwOqXEwxtLROfWKuQskK1J/cnoMAoGCCqGSM49BAMCA0gAMEUCIQC8ZqGyWiTl\r\n"
    "+HwjMpPGVuZXF7Nrc+T20Ul/cHNwvwy8TwIgS0sbf7Y8Q7tOO10gejq8BkparxfF\r\n"
    "weRljVcagySHkr8=\r\n"
    "-----END CERTIFICATE-----\r\n"
};

const uint8_t WISUN_CLIENT_CERTIFICATE[] = {
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIB1DCCAXqgAwIBAgIUWlMI0KJD20f4iECatOir+nYcIOIwCgYIKoZIzj0EAwIw\r\n"
    "KDEmMCQGA1UEAwwdV2ktU1VOIERlbW8gSW50ZXJtZWRpYXRlIDIgQ0EwIBcNMjQw\r\n"
    "NDI1MDM0ODI5WhgPOTk5OTEyMzEyMzU5NTlaMB0xGzAZBgNVBAMMEldpLVNVTiBE\r\n"
    "ZW1vIERldmljZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABCr2AJXlfI1Y8wQA\r\n"
    "eAIRrMhdLnEFZeDngj+lW6gOZ/t99aSGFQGcajLQdmx0cqfiKPVTEAt8EfDWa8+e\r\n"
    "6k95OhKjgYowgYcwDgYDVR0PAQH/BAQDAgOIMCEGA1UdJQEB/wQXMBUGCSsGAQQB\r\n"
    "guQlAQYIKwYBBQUHAwIwMQYDVR0RAQH/BCcwJaAjBggrBgEFBQcIBKAXMBUGCSsG\r\n"
    "AQQBgrdBAgQIAA1v//4gwBwwHwYDVR0jBBgwFoAU49VJIsQ0b3HYB9NctHkzXX1g\r\n"
    "q08wCgYIKoZIzj0EAwIDSAAwRQIhAJYknq+OtySbra+Rv/9nb67C60cuYsDY/VWu\r\n"
    "L+265XRqAiBayIrR6I5qF6nPfpjlF0awJMIIvxkMS2jNevzhalzWBg==\r\n"
    "-----END CERTIFICATE-----\r\n"
};

const uint8_t WISUN_CLIENT_KEY[] = {
    "-----BEGIN PRIVATE KEY-----\r\n"
    "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgZAmK06fre/qHDe2s\r\n"
    "1WTpSgzMRhj3k8aINVVFQKThkB6hRANCAAQq9gCV5XyNWPMEAHgCEazIXS5xBWXg\r\n"
    "54I/pVuoDmf7ffWkhhUBnGoy0HZsdHKn4ij1UxALfBHw1mvPnupPeToS\r\n"
    "-----END PRIVATE KEY-----\r\n"
};

#endif /* WISUN_TEST_CERTIFICATES_H_ */
