#ifndef WISUN_TEST_CERTIFICATES_H_
#define WISUN_TEST_CERTIFICATES_H_
#include <stdint.h>

const uint8_t WISUN_ROOT_CERTIFICATE[] = {
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIBozCCAUmgAwIBAgIUGeW6hMPie8WTjBAfwvsGRd1rCLMwCgYIKoZIzj0EAwIw\r\n"
    "HjEcMBoGA1UEAwwTV2ktU1VOIERlbW8gUm9vdCBDQTAgFw0yNDAxMzEwMzMzMDha\r\n"
    "GA85OTk5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTV2ktU1VOIERlbW8gUm9vdCBD\r\n"
    "QTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABHz5x4ITf2X9wEBO6FGipgRQ+2pr\r\n"
    "DQpiN+D34+CoNyvishmBI7UN1I4ZNJc4zj/XB49VPlh39hsevVFAJCgxXlujYzBh\r\n"
    "MBIGA1UdEwEB/wQIMAYBAf8CAQIwCwYDVR0PBAQDAgEGMB0GA1UdDgQWBBSMfOLK\r\n"
    "Kb52G2beBCX7McaVJV8XVzAfBgNVHSMEGDAWgBSMfOLKKb52G2beBCX7McaVJV8X\r\n"
    "VzAKBggqhkjOPQQDAgNIADBFAiEAy9Biv8of2ZoJRzikAVpnhyM3njzaYrPeYAxh\r\n"
    "hYCX50ACIBmxqqZ0FMI+2ak+pGyE98KI9Oo5qnjlG9o3Fvxfy9TB\r\n"
    "-----END CERTIFICATE-----\r\n"
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIBrTCCAVOgAwIBAgIUT1YZwStZ5NVMl8ncpVsHaJvlx6MwCgYIKoZIzj0EAwIw\r\n"
    "HjEcMBoGA1UEAwwTV2ktU1VOIERlbW8gUm9vdCBDQTAgFw0yNDAxMzEwMzMzMTBa\r\n"
    "GA85OTk5MTIzMTIzNTk1OVowKDEmMCQGA1UEAwwdV2ktU1VOIERlbW8gSW50ZXJt\r\n"
    "ZWRpYXRlIDEgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAS+/TCN7OCwsyg6\r\n"
    "+kmiNdPKk1Vbuf21vlJTAlrEiahRUBiExADKMYEkZK79Nnrc44Prp6ktT1NnhJdw\r\n"
    "YncABFV9o2MwYTASBgNVHRMBAf8ECDAGAQH/AgEBMAsGA1UdDwQEAwIBBjAdBgNV\r\n"
    "HQ4EFgQU82whQ3LP0SVw7XzG726kirD4CMAwHwYDVR0jBBgwFoAUjHziyim+dhtm\r\n"
    "3gQl+zHGlSVfF1cwCgYIKoZIzj0EAwIDSAAwRQIhALUE5e2VQHS8TNnGgtQ0PBIy\r\n"
    "EZN05A96khU3jdsZ+TalAiA/GJwvxXRpKxWzNIqAnLyZqjF84+47ydgRCb1vD7KX\r\n"
    "lw==\r\n"
    "-----END CERTIFICATE-----\r\n"
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIBtzCCAV2gAwIBAgIUeZFhB+x6QNr6ZBpGmN2R/HDo7NowCgYIKoZIzj0EAwIw\r\n"
    "KDEmMCQGA1UEAwwdV2ktU1VOIERlbW8gSW50ZXJtZWRpYXRlIDEgQ0EwIBcNMjQw\r\n"
    "MTMxMDMzMzExWhgPOTk5OTEyMzEyMzU5NTlaMCgxJjAkBgNVBAMMHVdpLVNVTiBE\r\n"
    "ZW1vIEludGVybWVkaWF0ZSAyIENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE\r\n"
    "XCJVvKlqtvcDXx4JJzigp+6z0wT9y7vMZz3d+C6Rk6H+j6Nqpx1ZLhbenq5cDt4q\r\n"
    "L46NpWStbWTlITaueLbf3qNjMGEwEgYDVR0TAQH/BAgwBgEB/wIBADALBgNVHQ8E\r\n"
    "BAMCAQYwHQYDVR0OBBYEFA3/gABX3vkrTS8QH4Sr+syQwP6lMB8GA1UdIwQYMBaA\r\n"
    "FPNsIUNyz9ElcO18xu9upIqw+AjAMAoGCCqGSM49BAMCA0gAMEUCIF9FPWlDxGuJ\r\n"
    "vCDuqtf6NNek02e7M4Om/YaVQHMIjm3EAiEAqG3qiQvFp7Uq/ATSWxwCOKEMBJxv\r\n"
    "iUfjSjPRaCyfLAE=\r\n"
    "-----END CERTIFICATE-----\r\n"
};

const uint8_t WISUN_CLIENT_CERTIFICATE[] = {
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIB1TCCAXqgAwIBAgIUT5qpQjIdPgj3ArTVwVjsSmHhCxwwCgYIKoZIzj0EAwIw\r\n"
    "KDEmMCQGA1UEAwwdV2ktU1VOIERlbW8gSW50ZXJtZWRpYXRlIDIgQ0EwIBcNMjQw\r\n"
    "MTMxMDMzMzE0WhgPOTk5OTEyMzEyMzU5NTlaMB0xGzAZBgNVBAMMEldpLVNVTiBE\r\n"
    "ZW1vIERldmljZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABJ6wvB+LFYwE+voe\r\n"
    "brMqstb5owA9jf9MTHQaDNNb0EpjzX/TpwWEQ/eqf3Sec0yTN4Em7mQnyzTUS/de\r\n"
    "OvzL3WejgYowgYcwDgYDVR0PAQH/BAQDAgOIMCEGA1UdJQEB/wQXMBUGCSsGAQQB\r\n"
    "guQlAQYIKwYBBQUHAwIwMQYDVR0RAQH/BCcwJaAjBggrBgEFBQcIBKAXMBUGCSsG\r\n"
    "AQQBgrdBAgQIAA1v//4gwBwwHwYDVR0jBBgwFoAUDf+AAFfe+StNLxAfhKv6zJDA\r\n"
    "/qUwCgYIKoZIzj0EAwIDSQAwRgIhANS2Dn88Xvbm0qZaWqp2i79v+DuU1Lc29rqz\r\n"
    "BAZyGyTaAiEA+GfIZ3R37kj7Ayk1JZusRGBgXBFZtErsnwc7/qFeQxg=\r\n"
    "-----END CERTIFICATE-----\r\n"
};

const uint8_t WISUN_CLIENT_KEY[] = {
    "-----BEGIN PRIVATE KEY-----\r\n"
    "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgeosQ0DUwEvjbqLBw\r\n"
    "nklAFAp8yr8fqUtAoTJc0xolZzqhRANCAASesLwfixWMBPr6Hm6zKrLW+aMAPY3/\r\n"
    "TEx0GgzTW9BKY81/06cFhEP3qn90nnNMkzeBJu5kJ8s01Ev3Xjr8y91n\r\n"
    "-----END PRIVATE KEY-----\r\n"
};

